export const CONFIG = {
    RULE_SETS: {
        HOME_PAGE_PERSONALIZATION: "HOME_PAGE_PERSONALIZATION",
        NEXT_GEN_FEATURE: "NEXT_GEN_FEATURE",
    },
    GLOBAL_CONFIGS: {
        GLOBAL_DDB_QUERY_VAL: "GLOBAL_DDB_QUERY_VAL",
        GLOBAL_DDB_VAL: "GLOBAL_DDB_VAL",
        GLOBAL_PARAM_STORE_VAL: "GLOBAL_PARAM_STORE_VAL",
        GLOBAL_S3_VAL: "GLOBAL_S3_VAL",
        GLOBAL_SECRET_VAL: "GLOBAL_SECRET_VAL",
        GLOBAL_STATIC_VAL: "GLOBAL_STATIC_VAL",
        TEST_SCHEMA_VAL: "TEST_SCHEMA_VAL",
    },
    LAMBDA_CONFIGS: {
        GET_PRODUCTS: {
            SLOT_NAMES: "SLOT_NAMES",
            FEATURED_PRODUCTS: "FEATURED_PRODUCTS",
        },
        TEST_LAMBDA: {
            TEST_STATIC_VAL: "TEST_STATIC_VAL",
            TEST_DDB_VAL: "TEST_DDB_VAL",
            TEST_HTTP: "TEST_HTTP",
        },
    },
};
